'use client';

import { TopBar } from '../components/TopBar';
import { DemoControls } from '../components/DemoControls';
import { HealthPanel } from '../components/HealthPanel';
import { NetworkTopology } from '../components/NetworkTopology';

export default function DemoLab() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100%' }}>
      <TopBar title="Demo Lab" subtitle="Controlled synthetic traffic injection · Real backend · No fake frontend states" />

      <div style={{ flex: 1, padding: 24, display: 'flex', gap: 20 }}>
        {/* Left: demo controls */}
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div className="gg-card" style={{ padding: 20 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
              <h2 style={{ fontSize: 15, fontWeight: 700, color: 'var(--gg-text)' }}>Synthetic Traffic Simulator</h2>
              <span style={{
                fontSize: 10, fontWeight: 700, padding: '2px 8px', borderRadius: 4,
                border: '1px solid rgba(245,158,11,0.3)', color: 'var(--gg-amber)',
                background: 'rgba(245,158,11,0.08)', letterSpacing: '0.06em', textTransform: 'uppercase' as const,
              }}>Controlled Synthetic Traffic</span>
            </div>
            <p style={{ fontSize: 12, color: 'var(--gg-muted)', marginBottom: 16 }}>
              Injects pre-configured flow profiles directly into the real detection API.
              All scores, evidence, and alerts are generated by the actual backend.
              No frontend-only simulation or fake data.
            </p>
            <DemoControls />
          </div>

          {/* Profile explanations */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 12 }}>
            {[
              {
                label: 'Normal Traffic',
                color: 'var(--gg-green)',
                items: ['TCP, ports 80/443', 'IAT ~50ms', 'Packets 10–80', 'Entropy ~5 bits', 'Expected: Benign'],
              },
              {
                label: 'SYN Flood',
                color: 'var(--gg-red)',
                items: ['SYN ratio 0.95–1.0', 'IAT <1ms', 'Tiny packets ~64B', 'Port 80', 'Expected: SYN/UDP Flood → HIGH/CRITICAL'],
              },
              {
                label: 'DNS Tunnelling',
                color: 'var(--gg-cyan)',
                items: ['UDP port 53', 'Entropy 7.2–8.0 bits', 'Packet length 170–220B', 'IAT 40–200ms', 'Expected: DNS Tunneling → HIGH'],
              },
              {
                label: 'C2 Beaconing',
                color: 'var(--gg-orange)',
                items: ['TCP port 443', 'IAT 1.8–2.2s (very regular)', 'Tiny packets ~125B', 'Duration 60–180s', 'Expected: C2 Beaconing → HIGH/CRITICAL'],
              },
            ].map((p) => (
              <div key={p.label} className="gg-card" style={{
                padding: 16,
                borderColor: `${p.color}30`,
              }}>
                <p style={{ fontSize: 12, fontWeight: 700, color: p.color, marginBottom: 10,
                  textTransform: 'uppercase' as const, letterSpacing: '0.06em' }}>
                  {p.label}
                </p>
                <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 4 }}>
                  {p.items.map((item) => (
                    <li key={item} style={{ fontSize: 11, color: 'var(--gg-text-2)', display: 'flex', gap: 6 }}>
                      <span style={{ color: p.color, flexShrink: 0 }}>·</span> {item}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>

        {/* Right: SIH demo sequence + topology */}
        <div style={{ width: 280, flexShrink: 0, display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div className="gg-card" style={{ padding: 20 }}>
            <p className="gg-label" style={{ marginBottom: 14 }}>SIH Demo Sequence</p>
            <ol style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 8 }}>
              {[
                'Start backend + frontend',
                'Dashboard loads → KPIs show live',
                'API health shows Operational',
                'Trigger NORMAL → verify benign flow',
                'Trigger SYN FLOOD → alert appears',
                'Open alert → see scores + evidence',
                'Trigger DNS TUNNEL → new alert',
                'Trigger C2 BEACON → detection',
                'View Detection Engine page',
                'View One-Way Architecture',
              ].map((step, i) => (
                <li key={i} style={{ display: 'flex', gap: 10, fontSize: 11, color: 'var(--gg-text-2)' }}>
                  <span style={{
                    width: 20, height: 20, borderRadius: '50%',
                    background: 'var(--gg-surface-2)', border: '1px solid var(--gg-border)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontSize: 9, fontWeight: 700, color: 'var(--gg-muted)', flexShrink: 0,
                  }}>{i + 1}</span>
                  {step}
                </li>
              ))}
            </ol>
          </div>

          <div className="gg-card" style={{ padding: 20 }}>
            <p className="gg-label" style={{ marginBottom: 14 }}>One-Way Architecture</p>
            <NetworkTopology />
          </div>

          <HealthPanel />
        </div>
      </div>
    </div>
  );
}

